### ISSUE TITLE
s2geometry ERROR

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#101]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Volodymyr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s2geometry-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s2geometry-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s2geometry-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Downloads\pokemongo-api-master\pokemongo-api-master\npm-debug.log

**Comment by stoffern** [comment]
@UAVova is there a ERR! before this log?
Do you have Visual Studio installed with Common Tools for Visual C++ ?

**Comment by UAVova** [comment]
@stoffern Yes, i'm sorry for not incliding that first
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(38): error C2504: 'exception': base class undef
ined (compiling source file ..\src\cell.cc) [D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\s2geom
etry-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(42): error C2614: 'std::bad_cast': illegal memb
er initialization: 'exception' is not a base or member (compiling source file ..\src\cell.cc) [D:\Downloads\pokemongo-a
pi-master\pokemongo-api-master\node_modules\s2geometry-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(59): error C2504: 'exception': base class undef
ined (compiling source file ..\src\cell.cc) [D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\s2geom
etry-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(63): error C2614: 'std::bad_typeid': illegal me
mber initialization: 'exception' is not a base or member (compiling source file ..\src\cell.cc) [D:\Downloads\pokemongo
-api-master\pokemongo-api-master\node_modules\s2geometry-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(38): error C2504: 'exception': base class undef
ined (compiling source file ..\src\cap.cc) [D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\s2geome
try-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(42): error C2614: 'std::bad_cast': illegal memb
er initialization: 'exception' is not a base or member (compiling source file ..\src\cap.cc) [D:\Downloads\pokemongo-ap
i-master\pokemongo-api-master\node_modules\s2geometry-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(59): error C2504: 'exception': base class undef
ined (compiling source file ..\src\cap.cc) [D:\Downloads\pokemongo-api-master\pokemongo-api-master\node_modules\s2geome
try-node\build\NativeExtension.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(63): error C2614: 'std::bad_typeid': illegal me
mber initialization: 'exception' is not a base or member (compiling source file ..\src\cap.cc) [D:\Downloads\pokemongo-
api-master\pokemongo-api-master\node_modules\s2geometry-node\build\NativeExtension.vcxproj]
```

**Comment by UAVova** [comment]
@stoffern Yes. VS 2015 Installed (including c++)

**Comment by stoffern** [comment]
This is errors in the s2geometry-node lib. Please report this to them.

**Comment by UAVova** [comment]
@stoffern I will. But since it is dependecy of this package, we are not able to use it?

**Comment by stoffern** [comment]
It compiles fine on my windows. Have you updated the dep?

**Comment by UAVova** [comment]
@stoffern Just now figured out that it is VS 15 Update 1-2 Error. Updating to 3 fixed the issue

**Comment by UAVova** [comment]
Since this issue is fixed, could you give me a link on how to start example? What i tried:
```
D:\Downloads\pokemongo-api-master\pokemongo-api-master>**node example/example.js**
D:\Downloads\pokemongo-api-master\pokemongo-api-master\example\example.js:1
(function (exports, require, module, __filename, __dirname) { import env from 'node-env-file'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
```
Also
```
D:\Downloads\pokemongo-api-master\pokemongo-api-master>**npm example**

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
```
