### ISSUE TITLE
Import to Browser

### ISSUE THREAD

**Issue by Skeec** [stoffern/pokemongo-api#103]
Hey Fellows

is it possible to run the api browser side too?
Or do some node modules only work in node environment and cannot be replaced?

Would be cool to have an api for browser so I dont necessarily need to run a server in the background all the time :+1:

**Comment by stoffern** [comment]
works everywhere you want it. ES6 can be compiled to support any javascript version with babel.
then NPM is version is already compiled to es5.

**Comment by gallexme** [comment]
@stoffern  u missing the c++ module for S2 so no it wont work in the browser
but
@Skeec You got to have a nodejs server sorry u cant use webpack/browserify i guess

**Comment by Skeec** [comment]
what does s2 exactly do? Maybe I could find a substitution :eyes:

**Comment by stoffern** [comment]
@Skeec it is a incomplete port of S2.
We have a issue on this here https://github.com/stoffern/pokemongo-api/issues/75
So we will find our own solution to this in the near future.

**Comment by Skeec** [comment]
ok so s2 tries to interpret niantic api response in geo cells or smthing like that?
Would be weird if s2 is the only module out there doing this kind of work am I right @gallexme ?

**Comment by gallexme** [comment]
@Skeec 
its the only one which works correct(almost no bugs, all features which we need) currently
othere pople are already trying something close to a js only port see
https://github.com/Armax/Pokemon-GO-node-api/pull/165
but the used library isnt "done"

**Comment by Skeec** [comment]
oh ok at which level does the pokemon go api rely on s2 library?
Aren't the returned pokemon and fort objects exact lat/lng points?

**Comment by stoffern** [comment]
GetMapObjects requires map cells

**Comment by Skeec** [comment]
I see what itself is a proto request

**Comment by stoffern** [comment]
@Skeec this is now a pure JS library and will work fine in all web browsers
