### ISSUE TITLE
"request" missing dep?

### ISSUE THREAD

**Issue by gre** [stoffern/pokemongo-api#108]
looks like the lib implicitely depends on `request`. When I try to use it it fails because of `Error: Cannot find module 'request'` in `pokemongo-api/dist/Auth.js:13:16`

should this be in package.json of the lib?
if you think it's up to lib user to provide it, then at least should be in peerDependencies.

**Comment by stoffern** [comment]
@gre looks we missed something. we converted over from `request` to `fetch`, and we did not get the Auth part. looking at it now.

**Comment by stoffern** [comment]
f169a12ed65286e50b809ab0bc973f959a3ef5c5
