### ISSUE TITLE
Wrong path (es5)

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#113]
When compiling project to ES5 using `npm run compile-example` and then trying to execute `node index.js`, you get:
`Error: Cannot find module './../example-es5/src/Player'`
And what is specially strange about it, is that even manually replacing **index.js** and **example.js** file to root folder, you still getting **example-es5** folder mentioned in the error output (Error: Cannot find module './../**example-es5**/src/Player'). Even if compile files from example folder directly to root folder

**Comment by stoffern** [comment]
check latest version.

**Comment by UAVova** [comment]
Emm, i don't think that adding 1 empty line should fix that :smile: 
Commit: https://github.com/stoffern/pokemongo-api/commit/1b56ea25c48a0e596d36fd537723add8a0a6ed04

**Comment by UAVova** [comment]
@stoffern I don't think that adding 1 empty line should fix that :smile: 
Commit: https://github.com/stoffern/pokemongo-api/commit/1b56ea25c48a0e596d36fd537723add8a0a6ed04

**Comment by stoffern** [comment]
Look, at the merge..  the commit is for npm publish

**Comment by UAVova** [comment]
@stoffern oh, so you been talking about this commit https://github.com/stoffern/pokemongo-api/commit/2e5ca391d5fb811b142aa96d9a9cc4da17f65abd ? 
If yes then i was having the latest version at the time when i was posting this issue

**Comment by stoffern** [comment]
dont know how you manage to do that, it works fine here.
@DaVarga can you help him out?

**Comment by DaVarga** [comment]
Cant reproduce this bug.

**Comment by stoffern** [comment]
@UAVova try using a clean example leave `example/index.js` and edit the `example/example.js`
npm run `compile-example` when you are done. works fine.
