### ISSUE TITLE
How to get the level of the current player ?

### ISSUE THREAD

**Issue by delmotte** [stoffern/pokemongo-api#115]

**Comment by gallexme** [comment]
@stoffern @jimmywarting 
to get the player level we got to enhance the get_inventory request
https://github.com/stoffern/pokemongo-api/blob/082277649ce2ef51ea1566e51dc79dfac5e4deb0/src/index.js#L112

the variable data should also contain
"player_stats"
where data.player_stats.level would be the player level i guess
https://github.com/stoffern/pokemongo-api/blob/b9b97e48385f935e58e347f3e3893dce67a44732/POGOProtos/Data/Player/PlayerStats.proto#L5

**Comment by stoffern** [comment]
@delmotte this is comming in the next update #134

**Comment by stoffern** [comment]
@delmotte latest update.
It will automaticly update the user object on login
so do:
```js
Poke.login(...)
console.log(Poke.player.level)
```

**Comment by delmotte** [comment]
thanks man !
