### ISSUE TITLE
FetchError: error with the api calls

### ISSUE THREAD

**Issue by syrys** [stoffern/pokemongo-api#121]
Hey Guys,

Was trying out this library and found that there are lot of errors coming through. For example, if i simply run the example file with correct login info and lat/lng, it pretty much crashes at about the 2nd api request (debugged using console/logs). 

So on the example, i commented out everything after the login call to the while loop. Then chucked all the content within the while loop inside a `try{/*code here*/}catch(e){console.log(e)};` except for the set timeout line. This is so i can debug. So, that means the api call resulting from `GetMapOnjects()` is getting called every 3 secs. About every 2nd time, i get an error that looks like this:

````
{ FetchError: request to https://pgorelease.nianticlabs.com/plfe/532/rpc failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (E:\LBDrive\Testing\pokemon-apis\2\node_modules\node-fetch\index.js:127:11)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'FetchError',
  message: 'request to https://pgorelease.nianticlabs.com/plfe/532/rpc failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
````

Thoughts? Is this expected?

**Comment by syrys** [comment]
nvm, it was my bad, ignore me :D

**Comment by syrys** [comment]
Also to add, even on the requests where it doesnt throw an error, the response to `GetMapObjects()` is pretty much empty, ie `catchable_pokemons, wild_pokemons, forts` are essentially empty arrays/objects (i can verify that the tested locations should have hits on most of those values).

**Comment by stoffern** [comment]
show us your code. it is working fine for everyone else.
There is a example project here: https://github.com/gallexme/pokemongo-api-example-project

**Comment by syrys** [comment]
@stoffern Thanks for getting back to me. Maybe you could help me.

So first of all, one of the problems is that im on Windows. This project doesnt work out of the box for me. `s2-geometry-node` doesnt work well with windows :( sucks, yes...

However, there seem to be another implementation `s2-geometry` (`https://github.com/Daplie/s2-geometry.js`) that is supposed to work fine. Claims to have it implemented on other competing libs. So i tried to mimic what they did here `https://github.com/Daplie/Pokemon-GO-node-api/blob/master/poke.io.js` with this library (`getNeighbors` function) using the mentioned `s2-geometry`. Afterwards, the codebase works, but im having the issue mentioned on the first post (again, im on windows, so i cannot compare sadly). 

Here is a copy of the project with the updates. main.js from the example added to the root.
`https://mega.nz/#!StsGXaAS!yMNXqg1P5XXrQW3hSm92gdG8uu9S7GHnzAAf1kXf2eA`
After downloading, simply run:
````
#fill in your login info on main.js
npm install
npm run main
````
Use a diff tool if you are worried tat it contains malicious code. Only changes i did was add and modify main.js, modified package.json to add the new lib and main script, then PlayerMap.js for the interrogation of new `s2-geometry`.

Any help appreciated, and would be great if this project can be migrated to not use `s2-geometry-node` if at all possible.

**Comment by stoffern** [comment]
`s2-geometry-node` needs Visual Studio 2015 installed to compile.

https://github.com/Daplie/s2-geometry.js is full of bugs. https://github.com/Armax/Pokemon-GO-node-api/pull/165#issuecomment-236428071
We are working on a new S2 port.. https://github.com/stoffern/pokemongo-api/issues/75

**Comment by syrys** [comment]
I see, thanks for that. I guess i probably have to wait for this port to work properly. :(

As for `s2geometry-node`, cant get it to work at all. Tried the VS you mentioned earlier, uninstalled and installed the C++ Build tools instead, neither worked. i have latest node and python 2.7 installed already, so its not that either. 

`npm install` errors out like this:
````
npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s2geometry-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s2geometry-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s2geometry-node
npm ERR! There is likely additional logging output above.
````

**Comment by stoffern** [comment]
https://github.com/stoffern/pokemongo-api/issues/101

**Comment by stoffern** [comment]
try installing the new version. it does not need a compile! :smile:

**Comment by syrys** [comment]
@stoffern awesome, so now the code can install without much fiddling around, thats great. So i downloaded the example repo you linked earlier and installed/ran. I still get errors while running the code, similar to my original post.

im going to remove some sensitive info from the logs with `<_SOMETHING_>`
````
Checking for login cache.
Could not read loginCache: Error: ENOENT: no such file or directory, open '<_MY_FOLDER_LOCATION_>\loginCache.json'
Logging in with regular auth.
[i] Logging with user: _MY_USERNAME_
[i] Login ok
[i] Session token: TGT-<_PART OF THE SESSION TOKEN_>-sso.pokemon.com
[i] Received PTC access token!
Login cache saved to file!
[!] Endpoint set: https://pgorelease.nianticlabs.com/plfe/500/rpc
[i] Received OK: GetPlayerResponse
{ FetchError: request to https://pgorelease.nianticlabs.com/plfe/500/rpc failed, reason: read ECONNR
ESET
    at ClientRequest.<anonymous> (<_MY_FOLDER_LOCATION_>\node_modules\node-fetch\index.
js:127:11)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'FetchError',
  message: 'request to https://pgorelease.nianticlabs.com/plfe/500/rpc failed, reason: read ECONNRES
ET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
````
i thought it may have been related to lat/long i chose, but i get the same error with the default lat/long on the example repo.

Any ideas?

**Comment by stoffern** [comment]
Show me your code

**Comment by syrys** [comment]
@stoffern my code is very simple. 
1. download/clone example project you linked: `https://github.com/gallexme/pokemongo-api-example-project`
2. `npm install`
3. edit the `/src/main.js` with ptc username/password, and lat/lng. I live in New Zealand, so im using a NZ Lat/Lng here. The account i use here is a dummy account i registered a week ish ago in ptc website. The account works on all the other python based api's out there, here is an example project that it works perfectly on: `https://github.com/AHAAAAAAA/PokemonGo-Map`.
4. `npm run main`. after running this for the first time, i got the error mentioned on the above comment. Running again and again, i get error like this:

````
<_MY_FOLDER_LOCATION_>>npm run main

> pokemongo-api-example-project@1.0.0 main <_MY_FOLDER_LOCATION_>
> babel-node src/main.js

Checking for login cache.
Logging in with cache.
Login cache saved to file!
{ FetchError: request to https://pgorelease.nianticlabs.com/plfe/rpc failed, reason: read ECONNRESET

    at ClientRequest.<anonymous> (<_MY_FOLDER_LOCATION_>\node_modules\node-fetch\index.
js:127:11)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'FetchError',
  message: 'request to https://pgorelease.nianticlabs.com/plfe/rpc failed, reason: read ECONNRESET',

  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
````

If you suspect this might be due to the user (again, works fine with the python based api's) or the lat/lng, if there is a way for me to get in touch with you privately, i can share these info with you.

Cheers.

**Comment by syrys** [comment]
@stoffern could this be some sort of a port issue on my end? not too familiar with node but googling for `ECONNRESET` talks about connection resetting on server's end, but if the port that is used to make the request is blocked on the client (my machine), that could likely happen too. Thoughts?

**Comment by gallexme** [comment]
@syrys  can u ping the pokemon servers?
try: ping pgorelease.nianticlabs.com

**Comment by syrys** [comment]
@gallexme yes, that works fine. about 26ms in that ping, no failures (tried few times).
Remember the code doesnt fail every time. I tested this requests on a loop with a slight delay (maybe 2-3 secs on each call, and restarted when ever it failed), so after couple of errors, it logges in and gets the endpoint, but sometimes it gets stuck in getting endpoint and i get something like this `Endpoint missing in request, lets try again.. in 5 seconds` few times in a row and it eventually fails with a `Too many consecutive "Missing endpoint" failures. Abandoning login`.

What i said above isnt 100% the case. The failure happens randomly (maybe 50% chance to fail on every request). Anyway, i just ran it again, the login and endpoint/inventory calls went through, then the `GetMapObjects()` ran few times before finally throwing an error. Started again from the beginning and this time it crashed on the first call.

any ideas?

**Comment by gallexme** [comment]
@syrys  sorry im not sure but i guess its your internet/router/firewall/antivirus or maybe just your pc doesnt like the nodejs libraries as other APIs work??

**Comment by stoffern** [comment]
This : 
```request to https://pgorelease.nianticlabs.com/plfe/rpc failed, reason: read ECONNRESET```
and this:
```Too many consecutive "Missing endpoint" failures. Abandoning login```

are 2 completly different errors.
the first one is you having connection problems.
the second one is the server overload.

You cannot get the second error if the first fails.

**Comment by syrys** [comment]
@stoffern yup i understand. But my main problem is the first error `request to https://pgorelease.nianticlabs.com/plfe/rpc failed, reason: read ECONNRESET`. No matter what i do, every couple of requests, this error comes up. It seems very random. As mentioned earlier, the python api code runs perfectly fine for me, but im a js based developer so i would prefer to get this working so i can tweak it around a bit.

@gallexme so, i have a pretty good interwebs connection (200/200 fibre). No out of the ordinary firewalls/applications installed, no antivirus installed. I cannot confirm/deny if my windows firewall is blocking it, but i didnt do anything special (to block or unblock, if it ever popped up and ask to add exception, i would allow it). i havent had any nodejs issues in the past, most of my work/code uses node/grunt/gulp to compile/build (not much more im afraid), but then again, i havent ever used a lot of the libraries used in this project before (i just have the latest node/npm from the website). Also, tested on 3 pcs, but they are all behind the same router/ip.

The only other thing i can think of, if you guys are not having this issue, could this be related to NZ? Maybe related to the niantic servers that im getting routed to? @stoffern, do you know if that could be caused by the servers end, or it only happens if the connection/libs on my end are messed up somehow?

Cheers.

**Comment by syrys** [comment]
I have a hacky way to get around it by putting the calls in individual try catch blocks and repeatedly calling them with a small timeout if it fails. 
between `GetPlayer()`, `GetInventory()`, and `GetMapObjects()`, they have about a 30-50% failure rate I can actually calculate it if you want :P. Also obviously the `GetMapObjects` return nothing for me (returns results for like santa monica pier), but thats likely because the bug they seem to still be working on with `s2-geometry`.

If anyone have any bright ideas for the above errors, do let me know :D

**Comment by stoffern** [comment]
why not just use the example?

**Comment by gallexme** [comment]
>i havent had any nodejs issues in the past, most of my work/code uses node/grunt/gulp to compile/build (not much more im afraid),

**Comment by syrys** [comment]
> why not just use the example?
> if you dont know js then just go direct to es6 syntax ?
@stoffern man, i dont think you understand my problem. Let me explain everything again. Forget everything earlier, and start here. First of all, my JS is fine, im somewhat new to es6 though, but i can follow it fine, im fairly new to node but i can also follow that fine too (just not all that familiar with all the common node libraries).

Alright, the problem. 

So, if you look at the example, there are only about 3 methods in it that results in an api call. These are: `GetPlayer()`, `GetInventory()`, and `GetMapObjects()` (this gets called over and over again). From trial and error, i have found that i have a 30-50% chance of getting a Error when running any method that results in a api call (methods mentioned above, + anything else i missed), and the error is this: `request to https://pgorelease.nianticlabs.com/plfe/rpc failed, reason: read ECONNRESET`. So, when i run the example, since there are no error handling, it just crashes and dies. It sometimes goes through couple of methods before dying, it sometimes doesnt even get past the first method, thus its very rare to even make it to the first `GetMapObjects()`. Does that make it clear why the example isnt usable for me?

So, as a result, i altered the example ever so slightly so i can test:
````
var api;
var player;
var inventory;
async function step1() {
  console.log('init starting...');
  try{
    //set player location
    Poke.player.location = {
      latitude: parseFloat(lat),
      longitude: parseFloat(lng)
    }

    //login
    api = await Poke.login(username, password, provider)
    setTimeout(step2, 3000);
  }catch (e){
    console.log(e);
    setTimeout(step1, 5000);
  }
}
step1();
async function step2() {
  try{
    player = await Poke.GetPlayer()
    console.log('step2 success');
    setTimeout(step3, 3000);
  }catch (e){
    console.log(e);
    setTimeout(step2, 5000);
  }

}
async function step3() {
  try{
    inventory = await Poke.GetInventory()
    console.log('step3 success');
    setTimeout(step4, 3000);
  }catch (e){
    console.log(e);
    setTimeout(step3, 5000);
  }

}

async function step4() {
  try {
    console.log('step4 Start');
    while( true ) {
      let objects = await Poke.GetMapObjects();
      console.log('catchable_pokemons', objects.catchable_pokemons.length);
      console.log('wild_pokemons', objects.wild_pokemons.length);
      console.log('forts.checkpoints', objects.forts.checkpoints.length);

      //just walk a little (1 - 15 meters..)
      await Poke.player.walkAround()
      await new Promise(resolve => setTimeout(resolve, 3000))
    }
    console.log('step4 Success');
  }catch (e){
    console.log(e);
    setTimeout(step4, 5000);
  }
}
````
with the above code, if an error happens, it will not crash, but it will simply wait few secs and retry the portion of the code that failed. Which for most part, works just fine, except i still see 30-50% error rate, so there is still an issue that needs to be addressed.

**Comment by gallexme** [comment]
could u ping the server while u doing the test?
connection reset means that the other end aborted the connection for some reason
it could be anything on the way to the ninantic servers, or their servers themself
:/ its not a API problem though, have u tried to put the same script on a server/different pc/different network/different country?

**Comment by syrys** [comment]
@gallexme so, i tried the script again yesterday, and magically its no longer throwing errors. Did absolutely nothing different on my end, its the exact same code from the day before. But now obviously the api isnt working because of the server update, so theres that... :(

> :/ its not a API problem though, 

Yes, i agree. However, whats the difference between this project vs the python based project? Because throughout all this, the python project always worked perfectly fine for me. As mentioned, im not a python dev, so i was keen to get this working instead so i can tweak/fiddle.

> have u tried to put the same script on a server/different pc/different network/different country?

Sorry, unfortunately not. I dont really have access to anything outside my network. But YOU essentially have the same code running on a different pc outside my network, and it works fine for you, and seems to work for most others. So only thing i can thing of is some sort of regional issue or local network issue (very unlikely), but then again, how can you explain the python script?

This really is a strange problem

**Comment by syrys** [comment]
> so, i tried the script again yesterday, and magically its no longer throwing errors.

PS. i should clarify, its no longer throwing errors as much. I still get them occasionally, but the rate has dropped to < 10%, which is an acceptable failure rate for me.
