### ISSUE TITLE
Google Auth Token

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#127]
```
 GoogleAccount(user, pass) {
    return new Promise( (resolve, reject) => {
      this.google.login(user, pass, ANDROID_ID, (err, data) => {
        if (data) {
          this.google.oauth(user, data.masterToken, data.androidId, OAUTH_SERVICE, APP_NAME, CLIENT_SIG, (err, data) => {
            if (err) reject(err)
            resolve (data.Auth)
          });
        }
        else reject(err)
      })
    })
  }
```
I'm wondering, is `data.masterToken` is just regular token that you can get using `google-api-nodejs-clien` for authentication? 
I'm asking because i want to try to implement authentication through google api (let users not to put their credentials in config file), but i don't really understand what is `masterToken `and `androidId `(one we get in the `data `object)

P.S: I know that it is not really an issue, but it seems to be the only way i can communicate with you guys) Thanks)

**Comment by gallexme** [comment]
@UAVova  similiar to this? https://github.com/stoffern/pokemongo-api/issues/83#issuecomment-236380287

also we got a chat on gitter where u can communicate with us
https://gitter.im/pokemongo-api/Lobby

**Comment by stoffern** [comment]
@UAVova is it as @gallexme says? Please close this issue or answer him
