### ISSUE TITLE
[Pokemon] setFavorite() does not seem to make pokemon a favorite

### ISSUE THREAD

**Issue by andnp** [stoffern/pokemongo-api#128]
When I run something to the effect of:
```
console.log(getAllFavorites().length) // gives 15
pokemonObject.setFavorite()
console.log(getAllFavorites().length) // gives 15
```
I notice that the number of pokemon favorited does not change. If I inspect this in the app, I notice the same, that the pokemon is not being favorited.

I'm getting no errors in the console.

```
[i] Received OK: SetFavoritePokemonResponse
```

**Comment by gallexme** [comment]
whats the result of setFavorite?
and show me your getAllFavorites function

**Comment by andnp** [comment]
I don't actually have a ```getAllFavorites``` function, it was more a demonstration of point. Given that the pokemon in the app are not being favorited from the API, I don't believe the bug would be in that code.

I'm getting ```{ SetFavoritePokemonResponse: { result: 2 } }``` which upon further investigation means the pokemon isn't being found. If I print out the pokemon object, it appears the ```id``` field exists and is set to a reasonable value.

**Comment by andnp** [comment]
If I were to have a ```getAllFavorites``` function, I suppose it would look something like:
```
function getAllFavorites() {
  return _.filter(inventory.pokemons, {favorite: 1});
}

**Comment by stoffern** [comment]
This works as it should. just checked.
Remeber to have a delay of you run it multiple times.

Added your function to the inventory class. 1d15b96923f8493f400b05a313a758abd51b9469

**Comment by andnp** [comment]
I'm guessing some recent updates must have fixed this. I was still able to reproduce before updating, but it has gone away after merging in recent changes.
