### ISSUE TITLE
Response error

### ISSUE THREAD

**Issue by BloodBowMain** [stoffern/pokemongo-api#130]
I have perfectly been using this project and am very grateful for the developers and great community helping each other out. I just wanna let u know, because I know how frustrating it may be, watching obvious failures (me) not being able to fix.

I have come to another problem, running the project at all. It all started after I'd done some few changes trying to come up with just a little more flexible system. I have tried to commented out any influencing edit, but cannot seem to get this work. This is my error:

> [!] Response error!
> Error: Response error!
>     at /pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:78:27
>     at Array.map (native)
>     at Connection._callee$ (/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:68:26)
>     at tryCatch (/pokemongo-api-example-project/node_modules/regenerator-runtime/runtime.js:62:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/pokemongo-api-example-project/node_modules/regenerator-runtime/runtime.js:336:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/pokemongo-api-example-project/node_modules/regenerator-runtime/runtime.js:95:21)
>     at step (/pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:29:191)
>     at /pokemongo-api-example-project/node_modules/pokemongo-api/dist/API.js:29:368
>     at run (/pokemongo-api-example-project/node_modules/core-js/modules/es6.promise.js:87:22)
>     at /pokemongo-api-example-project/node_modules/core-js/modules/es6.promise.js:100:28

CODE:
```
var lat = 63.434410
var lng = 10.411079

//var walklat = 63.4349676620381
//var walklng = 10.417098999023438

var openinput = false
var timesran = 0
var newcoords = []
var input = process.openStdin();


const Poke = new PokeAPI()



function retry(){
init()
}

/**
 * get the best ball from the {Inventory.items}
 * 
 * @param {Object}
 *            items That comes from the Inventory
 * @return {Item} The best ball you can use
 */

// function getBestBall(items) {
// return items.master_ball.count && items.master_ball ||
// items.ultra_ball.count && items.ultra_ball ||
// items.great_ball.count && items.great_ball ||
// items.poke_ball.count && items.poke_ball
// }



try{
async function init()  {

  Poke.player.location = {
    latitude: parseFloat(lat),
    longitude: parseFloat(lng),
  }
  
  let player = await Poke.GetPlayer()
  // let inventory = await Poke.GetInventory().inventory
  // let {items} = inventory

  const api = await Poke.login(username, password, provider)



  while( true ){

let cell = await Poke.GetMapObjects()    

for (let pokemon of cell.catchable_pokemons) {
	
	// let ball = getBestBall(items)

        await pokemon.encounter()
        
        // if (inventory.items.razz_berry.count){
        // await inventory.items.razz_berry.useCapture(pokemon)
        // console.log('definitivleyleyley have some berries!')
        // }
        // await setTimeout(function(){pokemon.catch(1)}, 3000)
        await pokemon.catch(2).catch(console.log)
        // await pokemon.encounterAndCatch().catch(err => console.log(err))
        //ball.count--
      }


for (let checkpoint of cell.forts.checkpoints) {
      if (!checkpoint.cooldown && checkpoint.withinRange) {
        let res = await checkpoint.search()
        console.log(res)
      }
    }

    // await Poke.player.walkToPoint(walklat, walklng)
    await Poke.player.walkAround()

//var dist = geolib.getDistance(
//        {latitude: lat, longitude: lng},
//        {latitude: walklat, longitude: walklng}
   //  )

//if(dist <= 12){
//openinput = true
//console.log('small distance')
//}
    
    console.log(Poke.player.location.latitude)
    console.log(Poke.player.location.longitude)

    if(openinput == true){
newwalkcoords()
}
    
    console.log('getting through')

    await new Promise(resolve => setTimeout(resolve, 3000))
  
  }
}

init().catch(console.log)
} catch(err) {

console.log('Trying again...')
retry()

}

function newwalkcoords(){
console.log('ran new func')
if(timesran == 0){


console.log('Enter new coords:')

input.addListener("data", function(d) {
    newcoords = d.toString().trim().split(",")
    walklat = parseFloat(newcoords[0])
    walklng = parseFloat(newcoords[1])
timesran = 0
openinput = false
  });

timesran = 1
  }

else{
timesran += 1
console.log('Already open…')
}


    
}
```

Thanks in regards!

**Comment by gallexme** [comment]
try adding 
await new Promise(resolve => setTimeout(resolve, 1000))
after each call u make to the server ^^
its normally because you are sending to much to the server

**Comment by BloodBowMain** [comment]
@gallexme done, and now I don't see why it should be too much for the servers. Same error message, doesn't look like it's getting far out in the code... Any idea why?

**Comment by stoffern** [comment]
@BloodBowMain please show us more of your logg before the error.
running latest version?

**Comment by BloodBowMain** [comment]
@stoffern but thats just it, the only messages before the error is me running the project:

> > babel-node src/main.js

**Comment by stoffern** [comment]
https://github.com/stoffern/pokemongo-api/blob/master/example/example.js

**Comment by andnp** [comment]
It would be useful to comment out all calls to the API one at a time to figure out which is failing. That or provide ```console.log``` debugging.

That being said, I'm willing to be the problem is that you are calling ```Poke.getPlayer()``` before ```Poke.login(...)```.

**Comment by BloodBowMain** [comment]
Calling getPlayer() before login was indeed the problem, thanks!
