### ISSUE TITLE
Assign pokemon to team gyms in area

### ISSUE THREAD

**Issue by Designer023** [stoffern/pokemongo-api#132]
Hi,

Not sure if this is a feature already but it would be great to be able to walk an area and auto assign (strongest|random) Pokemon to all my team's gyms with an available slot.

I'm not bothered about battling for ownership of gyms since that's quite fun, but it would be good to be able to support my local team where we already own a gym.

Thanks

**Comment by jimmywarting** [comment]
gym.deployPokemon(pokemon)

**Comment by Designer023** [comment]
Thanks @jimmywarting I will give this a try
