### ISSUE TITLE
Switch request to node-fetch

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#14]
Todo:
- [x] Switch over to fetch
- [ ] Save cookies to file

**Comment by stoffern** [comment]
Todo:
- [ ] Switch over to fetch
- [ ] Save cookies to file

**Comment by stoffern** [comment]
Do we need to save the cookies? actually?

**Comment by gallexme** [comment]
i think access to serialize/deserialize would be good enough
so that i "could" move a user from one node process to another without login in again

**Comment by jimmywarting** [comment]
It isn't really a cookie?
it's just a authentication token that get baked into the post request...?

**Comment by stoffern** [comment]
Lets skip cookies :)
