### ISSUE TITLE
Take over repo

### ISSUE THREAD

**Issue by DaVarga** [stoffern/pokemongo-api#143]
Some one interested in taking over this repo?
@jimmywarting
@gallexme 
@maxnowack

**Comment by gallexme** [comment]
im interested

**Comment by delmotte** [comment]
I'm okay to help if needed :)

**Comment by DaVarga** [comment]
@stoffern could you transfer the ownership of this repository and npm to @gallexme? I look forward to further collaboration and will investigatee package signature encryption tomorrow.

Thx

**Comment by rnd256** [comment]
@DaVarga, awesome, glad to hear you'll be looking into the unknown6/unknown22 issue.

In case this is helpful, apparently https://github.com/Armax/Pokemon-GO-node-api is a nodejs project that's already got it working. They're using this project to generate the unknown6 signature: https://github.com/SpencerSharkey/node-pogo-signature.

**Comment by maxnowack** [comment]
there is another node package which provides low level access to the protobuf requests: https://github.com/cyraxx/pogobuf

**Comment by stoffern** [comment]
i will fix it... give me 30 minutes :smile:

**Comment by stoffern** [comment]
added working signature to repo

**Comment by DaVarga** [comment]
thanks man! :)
