### ISSUE TITLE
[Inventory] Clean dupe pokemons

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#145]
Clean backpack for duplicate pokemons,
remove the ones with lowest CP.

**Comment by gallexme** [comment]
should be optional :D

**Comment by stoffern** [comment]
It will be a function.
`Player.inventory.clearDupePokemons()`

**Comment by gallexme** [comment]
i did such a thing already before we had the inventory:
https://gist.github.com/gallexme/cea4ec0550b56a91452dfb75eeabb587
cleans up by IV or by CP

**Comment by stoffern** [comment]
@gallexme why dont you create some PR`s and help the repo?
this would be good for the repo..

**Comment by gallexme** [comment]
@stoffern  cause im sitting 40h a week at work :/, can just share stuff which i make weekends sorry

**Comment by stoffern** [comment]
@gallexme ok :) I just find it wierd you made it and just dont copy it into a PR :)
I am also running 2 companies so this is on the spare time :smile:

**Comment by gallexme** [comment]
@stoffern  cause i did for the project which uses the api^^
before the whole inventory thing existed
and at work i could just drop in the lines into here, to maybe help you progress faster while i cant ^^
