### ISSUE TITLE
Create & Test functions

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#15]
- [x] Auth Google
- [x] Auth PTC
- [x] GetPlayer
- [x] GetInventory
- [x] GetMapObjects
- [x] CatchPokemon
- [x] EncounterPokemon
- [x] ReleasePokemon
- [x] UseItemPotion
- [x] FortSearch
- [x] FortDetails
- [x] FortDeployPokemon
- [x] FortRecallPokemon

**Comment by jimmywarting** [comment]
I'm using google auth, and it works fine

**Comment by stoffern** [comment]
check..
I would do recomend that you dont use your profile before the bot is complete :smile:
