### ISSUE TITLE
Better Explain the usage of it as Lib

### ISSUE THREAD

**Issue by gallexme** [stoffern/pokemongo-api#19]
#How do i Use it as a lib?
cloning it + npm install modyfing robot.js works fine

As Lib:
npm i -S github:stoffern/pokemon-go-api
creating .babelrc file with
`"presets": [
    "es2015",
    "stage-0"
  ],
  "plugins": [
    ["babel-project-relative-import", {
      "sourceDir": "src/"
    }]
  ],`
creating a main.js:

`import PokeAPI from 'pokemongo-api-js';`
telling it to run with 
"main": "babel-node"   src/main.js"
im stuck at 
Error: Cannot find module 'pokemongo-api-js'

would someone mind to create a example project please?

p.s i also tried pokemon-go-api as name

**Comment by stoffern** [comment]
@gallexme Yeah, the documentation is lacking.. will look at this tomorrow and monday..
meanwhile:

```
git clone https://github.com/stoffern/pokemon-go-api.git
npm i
npm run robot
```

**Comment by gallexme** [comment]
yeah thats what i got working already
but because i dont want to revert all my changes for each pull (or commiting my own/stashing them)
there has to be a way to use it as library

**Comment by stoffern** [comment]
@gallexme 
Yeah i completely understand..
let me fix it in about 7 hour :smile:

**Comment by stoffern** [comment]
@gallexme published to npm...
`npm i -S pokemongo-api`

**Comment by gallexme** [comment]
working nicely thank you
