### ISSUE TITLE
Problem with getInventory?

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#20]

**Comment by andnp** [comment]
Yup, I see it too.
I'm getting a ```[!] Response error!```

**Comment by InsOpDe** [comment]
Yes I get it, too - the error is
`[Error: Illegal wire type for field Message.Field .POGOProtos.Data.PokemonData.additional_cp_multiplier: 5 (0 expected)]`

**Comment by stoffern** [comment]
fixed and working : https://github.com/stoffern/pokemongo-api/commit/12c8c94aa86d75d247d8b8682355c1e7790c6b78

**Comment by InsOpDe** [comment]
still getting the same error

**Comment by stoffern** [comment]
@InsOpDe did you use the npm package?
it was not updated.. try to update now
`npm i -S pokemongo@0.1.9`

**Comment by InsOpDe** [comment]
solved it. according to [https://github.com/Armax/Pokemon-GO-node-api/blob/master/pokemon.proto#L313](another hub) the field `additional_cp_multiplier` in `PokemonData.proto` has to be a float, not an int32.

**Comment by jimmywarting** [comment]
Thanks, fixed
