### ISSUE TITLE
"walking"

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#21]
Just want to let you know that i have tried this: 

```javascript
  while( true ){
    await Poke.player.walkAround()
    let cells = await Poke.GetMapObjects()
    await new Promise(resolve => setTimeout(resolve, 10000))
  }
```

And it seems like i have walked 0.8 km while having this run for a while

**Comment by gallexme** [comment]
just a notice, you may should change 10000 to random value as im not sure how often the app sends the position and such
and it would look more "natural"

**Comment by jimmywarting** [comment]
You are right

**Comment by stoffern** [comment]
If you start the app and see the sphere around your player. this is the "hartbeat". it triggers GetMapObjects every 3 second.. so this should be set to that..

we should have a async function in the app running hartbeat..
Poke.player.activateHartBeat()

**Comment by jimmywarting** [comment]
I read somewhere that you should not go faster then 30 km/h

**Comment by stoffern** [comment]
okey.. i will slow it down a bit..

**Comment by stoffern** [comment]
Can anyone measure how fast it is moving? :smile:

**Comment by gallexme** [comment]
if my maths are correct : about 0.0008648601152618156 M each hartbeat

**Comment by jimmywarting** [comment]
Should calculate how fast can we loop to get ~ 30 km/h

**Comment by stoffern** [comment]
30km/h with hartbeat/walk every 3 second gives a max of 25 meters pr hartbeat.
Lets just set it to random 1,5-15meters

**Comment by gallexme** [comment]
walkToPoint is not really walking is it?
its just looping indefinitly fast and setting the location closer and closer to the destination?
also its not updating the server is it?
maybe we should add a sleep?

**Comment by stoffern** [comment]
Made a new issue on thisone: https://github.com/stoffern/pokemongo-api/issues/33

**Comment by jimmywarting** [comment]
> walkToPoint is not really walking is it?
its just looping indefinitly fast and setting the location closer and closer to the destination?
also its not updating the server is it?
maybe we should add a sleep?

@gallexme has a point. Nothing really happens (I think)
Maybe this should be incorporated into heartbeat?

instead of waiting till you reached the destination - set a desired destination that you want to walk to (like nearest pokestop/checkpoint) and use heartbeat to walk towards that destination instead of walking around randomly

**Comment by stoffern** [comment]
on the last update it should work fine.
Altho this is a loop that loops to the target on intervall and stops when it is complete.

I am thinking instead of doing:
```
GetMapObjects()
while(){
 ...
}
```
I wanna add togglers like this:
ToggleHartBeat()
TogglePokemonCatching()
TogglePokestopSearch()
ToggleBackpackCleaner()
ToggleWalkToTarget()

all async functions.. and that is all you need.
Altho i think walkToPoint should be one loop, and ToggleWalkToPoint should be a loop.
it can be confusing

**Comment by jimmywarting** [comment]
And do all the other stuff while you are walking towards the point

**Comment by stoffern** [comment]
exactly. 
But if you wanna make a loop yourself then you are free to use player.walkToPoint(lat,lng) in your own loop. (this will then just trigger once every time it is called)
