### ISSUE TITLE
EncounterPokemon response error

### ISSUE THREAD

**Issue by andnp** [stoffern/pokemongo-api#22]
We get a ```[!] response error``` when trying to encounter a pokemon.

**Comment by gallexme** [comment]
Same problem Stacktrace(if it might help):

> [!] Response error!
> Error: Response error!
>     at node_modules\pokemongo-api\dist\API.js:77:27
>     at Array.map (native)
>     at Connection._callee$ (node_modules\pokemongo-api\dist\API.js:67:26)
>     at tryCatch (F:\Entwicklung\Pokemon\bot\node_modules\regenerator-runtime\runtime.js:62:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (F:\Entwicklung\Pokemon\bot\node_modules\regenerator-runtime\runtime.js:336:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (F:\Entwicklung\Pokemon\bot\node_modules\regenerator-runtime\runtime.js:95:21)
>     at step (node_modules\pokemongo-api\dist\API.js:29:183)
>     at node_modules\pokemongo-api\dist\API.js:29:368
>     at run (F:\Entwicklung\Pokemon\bot\node_modules\core-js\modules\es6.promise.js:87:22)
>     at F:\Entwicklung\Pokemon\bot\node_modules\core-js\modules\es6.promise.js:100:28

code to reproduce:
`for (var pokemon of cell.catchable_pokemons) {
                try {
                    let encounterResult = await Poke.EncounterPokemon(pokemon);
                    let catchPokemonResult = await Poke.CatchPokemon(pokemon);
                    console.log({
                        encounterResult: encounterResult,
                        catchPokemonResult: catchPokemonResult
                    });

                } catch (error) {
                    console.log(error);
                }
            }`

**Comment by stoffern** [comment]
tnx looking into it..

**Comment by stoffern** [comment]
@gallexme @andnp should be fixed now..
Please update ticket if it works.

**Comment by gallexme** [comment]
[i] Received OK: EncounterResponse

**Comment by stoffern** [comment]
@gallexme i just fixed it.. try updating again :)

**Comment by gallexme** [comment]
@stoffern  u missed tagging it as 0.1.7, i guess npm wont update it without it if im fixed to 0.1.7
but

**Comment by stoffern** [comment]
oh i can see now that it captures the pokemon.. but it says response error..

**Comment by maxnowack** [comment]
@stoffern do you already have an idea how to fix the response error on `CatchPokemon`? anything I can help? :)

**Comment by gallexme** [comment]
@maxnowack  check #23
