### ISSUE TITLE
Todolist

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#24]
- [x] walk to point (human moving)
- [x] teleport to point
- [ ] while moving check if it is water.. (we are not jesus)
- [x] hartbeat every 3 seconds async loop - bind new data to .player....

**Comment by jimmywarting** [comment]
Someone put his phone on a drone and flew around with it. So for him water dosen't mather.

**Comment by gallexme** [comment]
im currently working on something like 
 walk to point

**Comment by stoffern** [comment]
:+1:  i dont have the time to code today..
possible tomorrow :smile: 

a little help on the way is:
```

  async walkToPoint(lat,long){

      let latMorP = Math.random() < 0.5 ? -1 : 1
      let latRand = ((Math.floor((Math.random() * 100) + 1))/10000000)*latMorP
      latMorP = Math.random() < 0.5 ? -1 : 1
      let longRand = ((Math.floor((Math.random() * 100) + 1))/10000000)*latMorP

      if (this.playerInfo.latitude > lat) 
        this.playerInfo.latitude = this.playerInfo.latitude-latRand
      else
        this.playerInfo.latitude = this.playerInfo.latitude+latRand

      if (this.playerInfo.longitude > lat) 
        this.playerInfo.longitude = this.playerInfo.longitude-longRand
      else
        this.playerInfo.longitude = this.playerInfo.longitude+longRand

      var distance = geolib.getDistance(
          {latitude: this.playerInfo.longitude, longitude: this.playerInfo.longitude},
          {latitude: lat, long}
      )
      //distance less than 10 meters?
      if (distance <= 10){
        return true
      }else{
        this.walkToPoint(lat,long)
      }

    })
  }
```

**Comment by gallexme** [comment]
my current code: 
https://gist.github.com/gallexme/43512b54fa6b4dfdd10236d25899585d

**Comment by stoffern** [comment]
oh, that looks to complexe :smile: 

when i have the time i will create a async hartbeat that takes GetMapObjectResponse every 3 second..
this will be put into Poke.player.surroundings
then a CatchPokemonIfAround, and walk to nearest checkpoint for fort :smiley:

**Comment by jimmywarting** [comment]
We also don't have to stand tight on the destination, you can stand a few meters from it...

**Comment by gallexme** [comment]
player.pokeStorage is not working because
 this.playerInfo.sessionData is never set
maybe add that to the list

**Comment by stoffern** [comment]
@gallexme this has nothing to do with the topic.
please create new issues if there are errors :)

**Comment by stoffern** [comment]
@gallexme pokeStorage solved: https://github.com/stoffern/pokemongo-api/commit/1d4b8660099e481376d2005472f98c146ac321a7

**Comment by jimmywarting** [comment]
How about not checking if it's water and just simply go to places worth going to instead of walking around randomly?
I doubt they will detect if a person is on water and ban them, there a airplains with wifi, bridges, boats, GPS coordinates inaccuracy
