### ISSUE TITLE
Change throw error to warn

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#25]
Change throw error to warn. 
Can be server error, and we can continue

**Comment by jimmywarting** [comment]
What?

**Comment by gallexme** [comment]
he probably means
that someone should change  such throw new Error('You should add a location name')
to warnings at places where its not to critical?

**Comment by jimmywarting** [comment]
Ok

**Comment by stoffern** [comment]
lets leave thisone for now :)
