### ISSUE TITLE
Passing data to pokemon class

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#26]
@jimmywarting how would we solve this:
we need to access, api, player from the Pokemon class.

should we just pass it down?

**Comment by gallexme** [comment]
cant be to bad
as a pokemon always belongs to 1 player
one small concern though, gyms pokemons they shouldnt try to access player/api

**Comment by jimmywarting** [comment]
If so can we pass it down only once? Kind och like

 Pokemon = require("Pokemon")(player)

**Comment by stoffern** [comment]
@jimmywarting there is alot of commits from me now.. 
check here i just passed it like this, but is it bad practice?
https://github.com/stoffern/pokemongo-api/blob/master/src/Pokemon.js#L14

We need to pass it every time we create a Pokemon.. 
- player coordinates change, and we need to update them
- api endpoint can also change..

**Comment by gallexme** [comment]
>player coordinates change, and we need to update them
>api endpoint can also change..
arent those in a  class instance?
which means u only hold a reference to the class? so all coordinates are updated always?

**Comment by jimmywarting** [comment]
What gallexme Said... But it also need API call.

But it is maybe bettet just to pass down Poke Class where we have access to everything?

**Comment by stoffern** [comment]
Pokemon and Fort class needs to access player coords, and the api.
the api class saves the auth_data so we cannot create a new class.

I think we need to pass down the Poke class so we can access all data in the store..

@jimmywarting do you have any better solutions? :smile:

**Comment by jimmywarting** [comment]
Hmm my idea is not so Good if you use this api and play as two player...

**Comment by stoffern** [comment]
yeah, i am blind :smile: 
well that is what i am doing now.. its passed into a prop called: this.parent.

should be ok..

**Comment by jimmywarting** [comment]
I think it's okey
