### ISSUE TITLE
Farm Pokestops

### ISSUE THREAD

**Issue by InsOpDe** [stoffern/pokemongo-api#27]
I can't find any code to actually "farm a Pokestop" as it is written in the TODO list

`[X] Farm specific area for pokestops`

I only see that it is checked whether a fort is a pokestop or a gym. Do I miss something?
I often have problems with the function-names as they dont provide enough information for me to know what they actually ment to do. (f.e.: `useGym`)

**Comment by gallexme** [comment]
it is entirely possible to farm pokestops with the current code,
just get the fort details, check if its a pokestop then walkto it
after that search it
useGym
uses a item(Item.js) on a specific gym

**Comment by stoffern** [comment]
as @gallexme said.

I will provide some easier code in a few hours..
it will be like:
```
     let cells = await Poke.GetMapObjects()
     for(let cell of cells) {
       if (cell.forts.length > 0){
         cell.forts.map(fort => {
           if (fort.isCheckpoint() && fort.withinRange()){
             fort.search()
           }
         })
       }
```

**Comment by jimmywarting** [comment]
`withinRange` is a smart thing to have, I will add it ;)
