### ISSUE TITLE
Remove setting location by name?

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#28]
I just think it's damm annoying to set/get location by name. For a bot and coding point of view it's just easier with lat/long

I think i want something like this
```javascript
class Player {
  get location(){
    return {latitude: playerInfo.latitude, playerInfo.longitude}
  }

  set location(coords){
    Object.assign(playerInfo, coords)
    return coords
  }
}
```

And then i want to remove `setLocation` & `teleport`

And altitude should always be 0

If you ever want to set location by name then use GeoCoder to figure out the x/y coordinates

`let {latitude, longitude} = await GeoCoder.geocode(place)`

-----

**Comment by gallexme** [comment]
maybe just add a method to setLocationByName(name)
and  use a location setter for long/lat

**Comment by stoffern** [comment]
@jimmywarting you can set location by name or location.. your choise:
```
{
  type: 'name',
  name:  'Times Square'
}
```
or 
```
{
  type: 'coords',
  coords:  {
    latitude: 40.759211,
    longitude: -73.984472,
  }
}
```

**Comment by jimmywarting** [comment]
honestly i want to remove `setLocation`all together

**Comment by stoffern** [comment]
yeah, that is acutally a good point :)
lets remove 'named locations'

@jimmywarting wanna create a PR?

**Comment by jimmywarting** [comment]
Sure
