### ISSUE TITLE
After a While Response Error

### ISSUE THREAD

**Issue by gallexme** [stoffern/pokemongo-api#29]
Not sure if its because of my code but i get this from time to time:
> [i] We just walked 3 meters
> [!] Response error!
> Error: Response error!
>     at /workspace/pokemon-farm/node_modules/pokemongo-api/dist/API.js:77:27
>     at Array.map (native)
>     at Connection._callee$ (/workspace/pokemon-farm/node_modules/pokemongo-api/dist/API.js:67:26)
>     at tryCatch (/usr/lib/node_modules/babel-cli/node_modules/regenerator-runtime/runtime.js:62:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/babel-cli/node_modules/regenerator-runtime/runtime.js:336:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/babel-cli/node_modules/regenerator-runtime/runtime.js:95:21)
>     at step (/workspace/pokemon-farm/node_modules/pokemongo-api/dist/API.js:29:191)
>     at /workspace/pokemon-farm/node_modules/pokemongo-api/dist/API.js:29:368
>     at run (/usr/lib/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:87:22)
>     at /usr/lib/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:100:28

i think it happens at  let player = await Poke.GetPlayer();
gonna try to find the cause

**Comment by stoffern** [comment]
Yeah, i get the same terror. I think it may be a server overload problem.
This needs futher investigation.

**Comment by InsOpDe** [comment]
Im getting it, too, from time to time: `[TypeError: Illegal buffer]`

**Comment by stoffern** [comment]
I think this has to do with server unstability and not the API.
The API is working fine, and by some reason it recieves a invalid or no response.

I will try to debug the error when i get it to see if the server is responding at all.

**Comment by gallexme** [comment]
ah not exactly
its like a disconnect
u got to reconnect when this happens
because everything throws a error

**Comment by stoffern** [comment]
@gallexme it is supposed to stop the script with a throw error so you dont spam the server after a error :)
The endpoints and authTicket is always updated for every request.

**Comment by stoffern** [comment]
Do we still have this problem?

**Comment by gallexme** [comment]
@stoffern  nope seems fixed
