### ISSUE TITLE
Split forts to pokestop and gym

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#30]
I was just thinking that this don't have so much in common and they require different method later 

```
       id: 'xxxx',
       last_modified_timestamp_ms: [Object],
       latitude: 0,
       longitude: 0,
       enabled: true,
       type: 1,
       owned_by_team: 0,
       guard_pokemon_id: 0,
       guard_pokemon_cp: 0,
       gym_points: [Object],
       is_in_battle: false,
       cooldown_complete_timestamp_ms: [Object],
       sponsor: 0,
       rendering_type: 0,
       active_fort_modifier: [Object],
       lure_info: null,
       parent: [Object],
       isGym: false,
       isCheckpoint: true
```

So i want to remove Fort class and create a Gym class and a Checkpoint ("Pokestop") class

What do you think?

**Comment by stoffern** [comment]
Yeah, sounds good.
Just so you know, in the communication part checkpoint and gym is both placed in the fort

I have not played Pokemon Go IRL yet, that is why i dont have all knowledge :smile:
