### ISSUE TITLE
..

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#32]
- [ ] Async loop - Hartbeat (GetPlayer and update Poke.player every 3 second async)
- [ ] Async loop - Check Poke.player.surroundings (catch if pokemons)
- [ ] Async loop - Go to nearest fort (Poke.player.walkTo, after x seconds change fort)

**Comment by gallexme** [comment]
anyone knows if pokemon servers may react allergic to multiple same async requests?

**Comment by stoffern** [comment]
It will not be a problem.
This is how the app works.
it sends hartbeat every 3 second when in map screen.
we just deactivate hartbeat temp when encounting
