### ISSUE TITLE
Getting error running example

### ISSUE THREAD

**Issue by Harrisandwich** [stoffern/pokemongo-api#37]
This is my current error running the example. Keep in mind, this may be due to my own lack of JS/Node know-how. 

/Users/joshzoff/PokemonGoDirections/routeFinder.js:16
async function init(Poke) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

I'm importing the api like this:

const PokeAPI = require("pokemongo-api");

**Comment by gallexme** [comment]
for async/await u need to use bable as it is es7 which nodejs doesnt support by default

**Comment by gallexme** [comment]
https://github.com/gallexme/pokemongo-api-example-project

clone it then
npm install
to run
npm run main

**Comment by stoffern** [comment]
@gallexme i think he wants a es5 example :smile:

**Comment by gallexme** [comment]
@stoffern  Dont see any reason why or where? :dancer:

**Comment by Harrisandwich** [comment]
@stoffern @gallexme hahah that would be great. I have never used ES6 and would like to make something that could be used on most web browsers. There are personal reasons for what I'm trying to accomplish, but I think other people would like to use it as well, so I would like to be able to host it.

**Comment by stoffern** [comment]
@Harrisandwich then listen up. ES6 and 7 is the future..
Babel compiles the script after you are finished and makes it all run in all browsers even the oldest ones..

download @gallexme example..
after you are finished your script and want to compile:
type: `babel --presets es2015,stage-0 -d compiled.js es6file.js`

then it works for all browsers that exsist

**Comment by Harrisandwich** [comment]
@stoffern That's pretty neat! Fair enough! I appreciate the help

**Comment by stoffern** [comment]
closing thisone..

**Comment by jimmywarting** [comment]
Perhaps you can just use the api as is?
We compile it to es5 when building

So you could just be fine using the api as promis

The example is just how you would do it with es6/7

await can only await a promise so most api's are promises

**Comment by weiry6922** [comment]
I'm having similar problems, never used babel, would like to learn to. Tried for a while using google etc but not sure how to use it with this project.

I've used npm install to get pokemongo-api, where would I go from here to get babel working?

I'm just a hobbyist so excuse any ignorance. Cheers.

**Comment by stoffern** [comment]
@weiry6922 
```
git clone https://github.com/gallexme/pokemongo-api-example-project
npm i
```
that should be all.
