### ISSUE TITLE
Fort : check for type before execute function.

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#38]
Add checks in functions.
example: `fort.search()` //have to be a checkpoint

**Comment by jimmywarting** [comment]
What dose search do?

Can we just move the search method to the checkpoint class instead of having it in the Fort class?

**Comment by gallexme** [comment]
search spins the pokestop(u get the items)
also u may should add a check for the cooldown

**Comment by jimmywarting** [comment]
There is nothing stoping us to click it even if it's to far away

I have added a method to get the distance to the fort
`console.log(fort.distance)`

Maybe should do something like:

if fort.distance < 10 && cooldown 
then search()

**Comment by stoffern** [comment]
i think we should add a cooldown timestamp the fort class when search is activated.
let me create a new issue on this.
fort.cooldownTimer
