### ISSUE TITLE
Add cooldown timer to checkpoints

### ISSUE THREAD

**Issue by stoffern** [stoffern/pokemongo-api#43]
when search() is activated we should add a timestamp and a function to check last time.
I think the cooldown is 5 minutes.

**Comment by jimmywarting** [comment]
I can confirm that it's 5 minutes
Took time once before

**Comment by jimmywarting** [comment]
Is it possible to convert a int64 long to a date object?

**Comment by gallexme** [comment]
the time is unix time

**Comment by jimmywarting** [comment]
Anyone know how big the circle around you are?
I mean: How far away can you stand from the checkpoint in order to take it?

Don't want to call search() on forts that are to far away...

**Comment by stoffern** [comment]
good question, i dont know..
move the bot 1 meter at the time and see the distance when it catches a pokemon..

**Comment by gallexme** [comment]
try 25m but i think it was 40 or 30 m

**Comment by jimmywarting** [comment]
Should also add a check if the bag is full

**Comment by gallexme** [comment]
then we don't have to call get inventory multiple times and it will become all synchronous

you got to check also pokeballs after catching, level ups, and more...
so maybe after all 5 min update it aswell?

**Comment by stoffern** [comment]
I think we should create sync function like Poke.ToggleBackpackCleaner and so on..

**Comment by jimmywarting** [comment]
Maybe will do something like that later

**Comment by jimmywarting** [comment]
What is left to do now after #46 has been done?
We have a Date object of when we can use it again that is null otherwice

i found out that a distance of 39 meter worked just fine

`console.log(fort.cooldown)` Date or null

**Comment by stoffern** [comment]
:+1: closing thisone
