### ISSUE TITLE
Add babel-polyfill

### ISSUE THREAD

**Issue by maxnowack** [stoffern/pokemongo-api#47]
If I try to use this lib via npm, I'm getting the following error:
````
ReferenceError: regeneratorRuntime is not defined
    at /Users/maxnowack/Code/pokepilot/node_modules/pokemongo-api/dist/Auth.js:44:36
    at /Users/maxnowack/Code/pokepilot/node_modules/pokemongo-api/dist/Auth.js:95:6
    at Object.<anonymous> (/Users/maxnowack/Code/pokepilot/node_modules/pokemongo-api/dist/Auth.js:183:2)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/maxnowack/Code/pokepilot/node_modules/babel-watch/runner.js:61:9)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
````

First I've thought, that it was my fault. But I've successfully tested babel transpilation with a simple `async / await`
Do you have any idea's why this error occurs?

**Comment by gallexme** [comment]
compare your project to mine
https://github.com/gallexme/pokemongo-api-example-project

**Comment by stoffern** [comment]
It is Babel polyfill.. You need it :)

**Comment by maxnowack** [comment]
I'm writing ES6/ES7 with babel to use `async` and `await`

**Comment by maxnowack** [comment]
@gallexme your script works for me. I've tried to copy over the dependencies and babel configuration to my project, but it doesn't work and I have no idea why. Now I'll take the other way: copy over my code to your project. That seems to work :D

**Comment by InsOpDe** [comment]
i believe you need the npm module `babel-polyfill` - that worked for me

**Comment by maxnowack** [comment]
I've tried that - It doesn't work for me

**Comment by stoffern** [comment]
@maxnowack do  you have the .babelrc file?
i will add babelpolyfill anyways..

**Comment by maxnowack** [comment]
Yes, I have a `.babelrc`

**Comment by stoffern** [comment]
Babel polyfill added here 9dbb560cb088d3357d6b16cad4844f91842a8ab2
Should now work with ES5
