### ISSUE TITLE
Evolve Pokemon

### ISSUE THREAD

**Issue by maxnowack** [stoffern/pokemongo-api#48]
In the proto files I've seen that there is a `EvolvePokemon` method which takes the `pokemon_id` as the only parameter. That looks very easy. Does someone already have some logic, to check if a pokemon can be evolved and the player have enough candies?
Candies in the inventory look like this:
````
"inventory_item_data": {
    "pokemon_data": null,
    "item": null,
    "pokedex_entry": null,
    "player_stats": null,
    "player_currency": null,
    "player_camera": null,
    "inventory_upgrades": null,
    "applied_items": null,
    "egg_incubators": null,
    "pokemon_family": {
        "family_id": 13,
        "candy": 36
    }
}
````

I think `family_id` is a the type of the candy and `candy` is the amount. It seems, that the `family_id` have to be mapped manually, since I haven't found a reference in the pokemon inventory data

**Comment by gallexme** [comment]
family_id = https://github.com/stoffern/pokemongo-api/blob/b9b97e48385f935e58e347f3e3893dce67a44732/POGOProtos/Enums/PokemonFamilyId.proto

EvolvePokemon  is already in the Pokemon.js

**Comment by jimmywarting** [comment]
We also have the Pokemon class that can tell you if there is a next evolution

```
        "prev_evolution":[
           {
              "num":"001",
              "name":"Bulbasaur"
           }
        ],
        "next_evolution":[
           {
              "num":"003",
              "name":"Venusaur"
           }
        ]
```
Comes from [pokedex.json](https://github.com/stoffern/pokemongo-api/blob/master/pokedex.json)

So we can do something like:
```javascript
pokemon = new Pokemon(props)
if(pokemon.next_evolution.length) {
  pokemon.envolve() // can be evolved
}
```

**Comment by maxnowack** [comment]
Okay, If you think that this is something that should be in this library, I'll make a PR

**Comment by maxnowack** [comment]
I've began with the evolution costs mapping, which I'd like to share: https://gist.github.com/maxnowack/f242af329897188575a705e3e70e0224

**Comment by gallexme** [comment]
the mapping is kinda useless, as it is in the DOWNLOAD_ITEM_TEMPLATES call
inside of pokemon_settings
