### ISSUE TITLE
[Question]Automatic Release Tagging?

### ISSUE THREAD

**Issue by gallexme** [stoffern/pokemongo-api#49]
@stoffern 
@jimmywarting 
how About automaticly increment the version and tag it on git for each push/commit
as the npm version is often far away from the git version

examples: https://docs.npmjs.com/cli/version

**Comment by jimmywarting** [comment]
I like github tags. But how do we get it to automatically publish on npm?

**Comment by gallexme** [comment]
npm version command automaticly
Bumps the version in package.json (the patch part)
Creates a commit with specified message(GIT)
Tags that commit with the new version(GIT)

**Comment by dougiefresh49** [comment]
I use this package called [semantic-release](https://github.com/semantic-release/semantic-release) (built by the crew at [egghead.io](egghead.io))

it will 
- auto bump versions based on commit messages (using [commitizen](https://www.npmjs.com/package/commitizen) standards)
- create git tags based on new version
- create release notes on the github page
- publish to npm
- etc

all with one command!

here are some links to short videos that show how to use them
[Semantic Release Setup](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release)
[Automatic release with Travis CI](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automatically-releasing-with-travisci)

**Comment by stoffern** [comment]
@dougiefresh49 nice i will look into it.

**Comment by stoffern** [comment]
@dougiefresh49 automatic publishing to npm now..
still missing git tags + release notes..

**Comment by dougiefresh49** [comment]
@stoffern nice!

And the reason you aren't seeing the git tags or release notes is because semantic-release relies heavily upon commits in the repo following the [commitizen](https://github.com/commitizen/cz-cli) standards when commiting changes. So from now on if you follow those standards when committing it will auto version and tag for ya 😎


[commitizen setup video](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-writing-conventional-commits-with-commitizen)

Let me know if you need any help

**Comment by stoffern** [comment]
@dougiefresh49 is it possible to have multiple commit in one version?
to me it looks like it will tag and push to npm everytime you commit to master?

What if you create a PR, dont Travis CI run then aswell and publish to? :smile:

**Comment by dougiefresh49** [comment]
@stoffern yup! so rule of thumb is that you would develop on a feature or fix branch and then open a PR every time you have set of code ready to publish. 

so if your feature is to evolve pokemon then you might have a branch called (for example)
`feature/evolve-pokemon`

and you might have some commits to that branch like 

` feat(evolve): add evolve functionality to Pokemon class`
`test(evolve): add tests for pokemon evolve `

```
fix(evolve): fix some issue with evolve

some description of how you fixed the issue

closes #111111111111
```

and then you can open the PR and merge to master, thus keeping your master branch as the 'sacred always working (hopefully)' branch

**Comment by dougiefresh49** [comment]
I used it on a simple repo [here](https://github.com/dougiefresh49/project-euler)

And you can see what the old PR looked like [here](https://github.com/dougiefresh49/project-euler/pull/5)

This helps eliminate any bad code reaching the master branch. And if others want to contribute, they can do the same or by the same process with their forked repo.

**Comment by stoffern** [comment]
This is currently working.
Release tags and release notes are not created on github.
@dougiefresh49 any ideas?

I am using `git add .` `git cz` and `git push`
