### ISSUE TITLE
sessionData / PokeStorage

### ISSUE THREAD

**Issue by InsOpDe** [stoffern/pokemongo-api#50]
I cannot find the piece of code which stores the `sessionData` except for ` set profileDetails` but this doesnt get called anywhere. Neither can I find a call for getting all captured pokemons (except for `get pokeStorage()` of course which is dependant of ` set profileDetails`)
Am I missing something?

**Comment by stoffern** [comment]
this solve the issue https://github.com/stoffern/pokemongo-api/commit/1d4b8660099e481376d2005472f98c146ac321a7

**Comment by InsOpDe** [comment]
We are now only getting information like `max_pokemon_storage` - not the actual pokemon in our storage

**Comment by stoffern** [comment]
True, need to figure out what call that fetches the pokemon data.
then we can add that to the storage.

**Comment by InsOpDe** [comment]
my mistake, you can get all your pokemon through `GET_INVENTORY`
