### ISSUE TITLE
Nearby pokemon

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#51]
We don't have much to go on

```
"pokemon_id": 41,
"distance_in_meters": 200,
"encounter_id": {...}
```

If i find a uniq pokemon, then i want to chase it. But how?

**Comment by stoffern** [comment]
This can be a little tricky since you only get the distance.
You can get data from surroutings at a distance of 200 meters. 
But that will automaticly put your GPS print in that place you are checking (jumping around in 200 meters..)

Then it would have to trigger a sort of walkInACircle around point?

**Comment by jimmywarting** [comment]
Hehe that could work if the distance_in_meters wasn't always 200m

and by the way i think it's 100, 200 & 300m 
each paw represent 100 meters

**Comment by gallexme** [comment]
i think its 
<100
<200
>200
as 200 is the maximum u get

**Comment by stoffern** [comment]
Then you have to run 100 meters in all directions to figure what direction it is :smile:

**Comment by stoffern** [comment]
I think i have solution to this. Actually i have a solution to see the complete world map from one location :)

**Comment by jimmywarting** [comment]
How?

**Comment by stoffern** [comment]
Dont know if it is possible but that would be to alter the cells you request from the server.
If it is 200 meter away it is in 1 out of 8 cells. and if it is 400 meters away it is in a radius of 2 cells.

Altering cells with a different center could work.

**Comment by stoffern** [comment]
Not possible, just tested it out. seems like you still are fixed down to the area of lat long.
Forts is not related to lat-long when you send request. so it is possible to get full world map from one location. but that is not what this is about.

Closing issue as it is not possible :disappointed:
