### ISSUE TITLE
How will the request to the server. the query profile information

### ISSUE THREAD

**Issue by windd32** [stoffern/pokemongo-api#62]
https://github.com/windd32/Conect-pokemon/blob/master/main.pass 

my connection I get the token. What next don't know

**Comment by stoffern** [comment]
see the example:
https://github.com/stoffern/pokemongo-api/blob/master/example/example.js

**Comment by windd32** [comment]
which url address we should send POST to get information about profile

**Comment by stoffern** [comment]
https://github.com/stoffern/pokemongo-api/blob/master/src/API.js#L108

**Comment by gallexme** [comment]
he wants to write his own api ...

**Comment by stoffern** [comment]
@windd32 I dont think we should use the time to teach you how it all works.
Please read the code or use forums to figure out how the communication works.
