### ISSUE TITLE
Add Inventory Class?

### ISSUE THREAD

**Issue by gallexme** [stoffern/pokemongo-api#64]
We may should add a Inventory.js which contains Item(.js) and Pokemon(.js)
and gets loaded from Poke.GetInventory ?
for now it is a real hassle to work with the inventory with 
let inventory = await Poke.GetInventory();
inventory.GetInventoryResponse.inventory_delta.inventory_items

**Comment by stoffern** [comment]
@gallexme will look into it when i have fixed travis and versioning :)

**Comment by gallexme** [comment]
currently working on it

**Comment by jimmywarting** [comment]
Most method in the Item class is meant to be in a Inventory?
I mean You can't use hp & revive on the same item...


This is what i had in mind...

```javascript

/**
 * This will hold an array with items that you have
 */
class Items extends Array {
  constructor(){
    super()
  }



  /**
   * Adds the items from a checkpoint in to the Inventory
   */
  add() {
  }



  /**
   * Gets the best ball you can use
   * agains a pokemon you are trying to catch
   * 
   * @return {Item} the poke ball you can use
   */
  get bestBall() {
    // See https://github.com/stoffern/pokemongo-api/blob/b8211baf6235b60a4a40628c83fd2049faf6b9cd/example/example.js#L16
  }
}



/**
 * This will hold an array with pokemons that you own
 */
class Pokemons extends Array {
  constructor() {
    super()
  }
}



/**
 * This will hold an array with eggs that you own
 */
class Eggs extends Array {
  constructor(){
    super()
  }
}



class Inventory {
  constructor(){
    this.items = new Items
    this.pokemons = new pokemons
    this.eggs = new Eggs
  }



  /**
   * Updates the inventory from the cloud
   * @return {Promise} Resolves to true/false if success
   */
  update() {
  }

}

export default Inventory
```

```javascript
async login(...){
   this.player.inventory = new Inventory()
   await this.api.setEndpoint(this.player.playerInfo)
   await this.player.inventory.update()
}

**Comment by gallexme** [comment]
Inventory.update()
should update the inventory by deltatime so that u only get the changeset 
so im not sure if we should store Items/Eggs/Pokemons in a array
as the time has to be respected

**Comment by jimmywarting** [comment]
@gallexme Will you make a PR?

**Comment by gallexme** [comment]
nope no time

**Comment by stoffern** [comment]
An i am at the hospital, back tomorrow;)

**Comment by gallexme** [comment]
k
if its not done until the weekend i will do it saturday/sunday

**Comment by jimmywarting** [comment]
I started on the inventory, it's not included in the API yet, but it's up there in the source for you to improve upon, it can also be totally rewritten if you feel like coming up with something better. I have not even figure out yet how it's going to be

**Comment by stoffern** [comment]
What is missing here, or what do we need to do?

**Comment by jimmywarting** [comment]
@stoffern Well, if you look at the [Inventory.js](https://github.com/stoffern/pokemongo-api/blob/master/src/Inventory.js) then it's only half finish

**Comment by stoffern** [comment]
@jimmywarting completing thisone now

**Comment by stoffern** [comment]
@jimmywarting how would it be best to attach the Inventory class to the GetInventory()

```js
inventory{
  items: []
  pokemons: []
  eggs: []
  candies: []
}
```

**Comment by gallexme** [comment]
@stoffern  maybe inventory from  inventory_delta.inventory_items
so that it can be easily updated from delta informations?

**Comment by jimmywarting** [comment]
As I mention above:

```javascript
async login(...){
   this.player.inventory = new Inventory()
   await this.api.setEndpoint(this.player.playerInfo)
   await this.player.inventory.update() // update the inventory on initial
}
```
