### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by BloodBowMain** [stoffern/pokemongo-api#66]
Hi, I'm new to this sort of program (nodejs) and therefore is not very good at resolving all of my problems occurring while trying to run this project. I have set up a Pokemon Go MITM proxy but I do not think that it is correlated to this (https://www.npmjs.com/package/pokemon-go-mitm).

I would love to get a little more detailed wiki where at least I get to know how to run the example file. Thanks in regards!

**Comment by stoffern** [comment]
cc @gallexme want to help him out? your example is outdated as we changed the GetMapObjectsResponse.

**Comment by gallexme** [comment]
Sure will update my example project after lunch

**Comment by gallexme** [comment]
@BloodBowMain 
try to clone my example project(https://github.com/gallexme/pokemongo-api-example-project)
git clone https://github.com/gallexme/pokemongo-api-example-project.git
cd pokemongo-api-example-project
npm install
npm run main

**Comment by BloodBowMain** [comment]
@gallexme thank you so much! Just one thing: looks like the environment file doen't exist (/pokemongo-api-example-project/src/.env)

**Comment by gallexme** [comment]
@BloodBowMain  thanks,removed it

**Comment by BloodBowMain** [comment]
@gallexme So sorry for not getting this to work, but now it's nagging about a 01_proxy.js... 
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   '01_proxy.js' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose stack Error: missing script: 01_proxy.js
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
5 verbose cwd /Users/AbelPuz/pokemon-go-mitm-node/node_modules/http-mitm-proxy/test
6 error Darwin 15.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "01_proxy.js"
8 error node v6.3.1
9 error npm  v3.10.3
10 error missing script: 01_proxy.js
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
 `

**Comment by stoffern** [comment]
it has reference to `pokemon-go-mitm-node` that is not this repo..

**Comment by BloodBowMain** [comment]
@gallexme  Fixed a wrong reference problem, but seems to get this error: 
_TypeError: cells[Symbol.iterator] is not a function_
Don't know if this is due to something I have set up wrong.
Thanks a lot for helping, really appreciate it!

**Comment by AutomatonSystems** [comment]
@BloodBowMain The object that comes back from Poke.GetMapObjects() is not an array of cells since API 0.2.0 released today, all the data is pushed into one object instead. So the for(let cell of cells) loop is no longer required. This one isn't a problem on your side; the example is just out of date :)

**Comment by BloodBowMain** [comment]
@AutomatonSystems Ah, didn't see that, thanks!

**Comment by sai22312** [comment]
sorry to say, i didn't understand how to run the project , can you please provide step wise instructions. i have downloaded the zip file. let me know the next steps...
