### ISSUE TITLE
Releasing Pokemons not working

### ISSUE THREAD

**Issue by gallexme** [stoffern/pokemongo-api#68]
not sure how to get more data then console.logging it
```
releasing Vulpix
[i] Received OK: ReleasePokemonResponse
{ ReleasePokemonResponse: { result: 3, candy_awarded: 0 } }
Pokemon {
  pokemon_id: 37,
  cp: 10,
  stamina: 10,
  stamina_max: 10,
  move_1: 209,
  move_2: 131,
  deployed_fort_id: 0,
  owner_name: '',
  is_egg: false,
  egg_km_walked_target: 0,
  egg_km_walked_start: 0,
  origin: 0,
  height_m: 0.6230424046516418,
  weight_kg: 10.259743690490723,
  individual_attack: 10,
  individual_defense: 7,
  individual_stamina: 2,
  cp_multiplier: 0.09399999678134918,
  pokeball: 1,
  captured_cell_id: Long { low: 0, high: 1201256704, unsigned: true },
  battles_attacked: 0,
  battles_defended: 0,
  egg_incubator_id: '',
  creation_time_ms: Long { low: 499975783, high: 342, unsigned: true },
  num_upgrades: 0,
  additional_cp_multiplier: 0,
  favorite: 0,
  nickname: '',
  from_fort: 0,
  num: '037',
  name: 'Vulpix',
  img: 'http://www.serebii.net/pokemongo/pokemon/037.png',
  type: 'Fire',
  height: '0.61 m',
  weight: '9.9 kg',
  candy: '50 Vulpix Candy',
  egg: '5 km',
  multipliers: [ 2.74, 2.81 ],
  weaknesses: [ 'Water', 'Ground', 'Rock' ],
  next_evolution: [ { num: '038', name: 'Ninetales' } ],
  catchable: true,
  parent: 
   PokemonGOAPI {
     player: 
      Player {
        parent: [Circular],
        playerInfo: [Object],
        Auth: [Object],
        surroundings: [Object] },
     api: 
      Connection {
        parent: [Circular],
        endPoint: 'https://pgorelease.nianticlabs.com/plfe/208/rpc',
        auth_ticket: [Object] },
     map: PlayerMap {},
     logged: false,
     debug: true,
     useHeartBeat: false } }
```

**Comment by gallexme** [comment]
i guess i know why
Pokemon.js
expects something like this but this is only the response in map cells

{ encounter_id: Long { low: -1163477523, high: 2066077743, unsigned: true },
  last_modified_timestamp_ms: Long { low: 682095647, high: 342, unsigned: false },
  latitude: 000000000000000000CUT,
  longitude:000000000000000000CUT,
  spawn_point_id: '4799c1318f5',
  pokemon_data: 
   { id: Long { low: 0, high: 0, unsigned: true },
     pokemon_id: 41,
     cp: 0,
     stamina: 0,
     stamina_max: 0,
     move_1: 0,
     move_2: 0,
     deployed_fort_id: 0,
     owner_name: '',
     is_egg: false,
     egg_km_walked_target: 0,
     egg_km_walked_start: 0,
     origin: 0,
     height_m: 0,
     weight_kg: 0,
     individual_attack: 0,
     individual_defense: 0,
     individual_stamina: 0,
     cp_multiplier: 0,
     pokeball: 0,
     captured_cell_id: Long { low: 0, high: 0, unsigned: true },
     battles_attacked: 0,
     battles_defended: 0,
     egg_incubator_id: '',
     creation_time_ms: Long { low: 0, high: 0, unsigned: true },
     num_upgrades: 0,
     additional_cp_multiplier: 0,
     favorite: 0,
     nickname: '',
     from_fort: 0 },
  time_till_hidden_ms: 490261 }

**Comment by gallexme** [comment]
#69

**Comment by AutomatonSystems** [comment]
Not sure if you noticed but the `Pokemon.release()` is passing in `this.pokemon_id` which is the pokedex number of the pokemon; it should be passing in `this.id`

**Comment by gallexme** [comment]
yep i did that with #69

**Comment by DaniVarga** [comment]
Would some one merge pls #78?
