### ISSUE TITLE
Add version property to package.json

### ISSUE THREAD

**Issue by DaVarga** [stoffern/pokemongo-api#70]
Please provide version property in the package.json inside of this repo. Without the property i cant install pokemongo-api directly from this repo with npm.

I've added pokemongo-api to my package.json.
```  
"dependencies": {
	"pokemongo-api": "git+ssh://git@github.com:stoffern/pokemongo-api.git#master"
}
```

I get the following error while npm install.

```
$ npm install       
npm ERR! addLocal Could not install /tmp/npm-13457-fd052020/git-cache-69ce1e44/bc42ca83530f595a17edc20dcd9609b3a780f353
npm ERR! Linux 4.6.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! No version provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/daniel/NodeProjects/botemon-stay/npm-debug.log
```

**Comment by DaVarga** [comment]
Added Pr #71

**Comment by stoffern** [comment]
Install from npm. We use Travis to autorelease commits. Adding version to package.json will stop it from working.. ;)

**Comment by dougiefresh49** [comment]
@DaVarga you can actually put it as 
`"version": "0.0.0-semantically-released",`
and this will alleviate any issues and not conflict with semantic-release

**Comment by stoffern** [comment]
Version added 9f2a4b4b592e83c0483bed2e14aa289213af1038
