### ISSUE TITLE
How to give raspberry to Pokèmon?

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#72]
Want to make it easier to catch Pokémon... But how?

Started to work on that here: https://github.com/stoffern/pokemongo-api/blob/ca9f8e0107c5b71d12fe9dce7f44c69e1d92c0b6/src/Pokemon.js#L105

**Comment by gallexme** [comment]
take the raspberry from inventory and do
raspberry.useCapture(pokemon) ?

**Comment by jimmywarting** [comment]
Thanks it worked, it was an error in the useCapture, but i fixed it.

I really wish i had a Inventory class now...
