### ISSUE TITLE
GetMapObjects returns weird and incostisten cell coverage 

### ISSUE THREAD

**Issue by l1bbcsg** [stoffern/pokemongo-api#75]
Here's an example of image I get visualizing S2 cells returned by `GetMapObjects`. The blue marker represents player location. The shape is seemingly random:

![image](https://cloud.githubusercontent.com/assets/1044684/17170013/6ac644ee-5414-11e6-91c7-bc1a3424752e.png)

If I move some 0.01 degrees I get even weirder image that is also very different from the previous location:

![image](https://cloud.githubusercontent.com/assets/1044684/17170019/7354944e-5414-11e6-830b-0698ee2216eb.png)

With this behavior it's impossible to reliably cover an area scanning every cell and also avoiding overlapping and duplicate requests.

**Comment by gallexme** [comment]
weird

**Comment by l1bbcsg** [comment]
No, this is actually what `PlayerMap.getNeighbors` calculates. The library requests wrong cell structure and gets a valid response with the same cells from niantic backend.

**Comment by stoffern** [comment]
This is related to a bug in s2geometry-node
https://github.com/billyriantono/s2geometry-node/issues/9#issuecomment-235609506

**Comment by r-tanner-f** [comment]
I don't think this is a bug in s2geometry-node. The Python library s2sphere gives the same results. 

I'm guessing the `getNeighbors` method is just copy-pasta from the Python bot [here](https://github.com/Mila432/Pokemon_Go_API). It's not very effective. Unfortunately, s2geometry-node [doesn't expose getCovering yet](https://github.com/billyriantono/s2geometry-node/issues/13), so without fixing that there isn't much of a good way to generate a rectangle that I've found.

If you make the cell bigger, Niantic's servers will truncate the response (basically an empty, useless response.) If you change the number of cells, you get back an empty array (`{ cells: [] }`). 

Somehow we need to get the surrounding area using eleven level 15 (or smaller) cells, and do it either without the use of S2LnLngRect and getCovering, or by fixing getCovering.

**Comment by stoffern** [comment]
@r-tanner-f that is almost correct, we have ported the code from [pgoapi](https://github.com/tejado/pgoapi). I am not that familiar with geo cells but will look more into it. If you have any directions or ideas how to solve it you are welcome to create a PR

**Comment by stoffern** [comment]
@l1bbcsg How did you get to see the map coverage from the cells you have?

I am creating a new S2 cell function to get 11 level 15 cells plotted in a square around your position.
Need to check it out if it works when its done :smile:

**Comment by l1bbcsg** [comment]
@stoffern I used http://s2map.com/ - it's a great tool for visualizing anything S2 related. You can paste ids/tokens and it'll plot them.

**Comment by stoffern** [comment]
Finally #124
Solvs all map problems.
Moved over to pure JS and cells are now as correct as they can be.
