### ISSUE TITLE
npm release falling behind

### ISSUE THREAD

**Issue by AutomatonSystems** [stoffern/pokemongo-api#82]
The latest release on npm is 0.2.0 which is before the fixes to Pokemon.release() and the GetInventory response+Items improvements. Can someone with the power push out 0.2.1 so I can start playing with the new data please?

**Comment by stoffern** [comment]
I know, currently I am the only one with access to that. Still in the hospital but will be back tomorrow so I can fix it ☺

**Comment by stoffern** [comment]
Synced.
