### ISSUE TITLE
GetMapObjects returns undefined

### ISSUE THREAD

**Issue by BloodBowMain** [stoffern/pokemongo-api#85]
As said in the title, when I loop through the mapobjects to check for a checkpoint (pokestop), it wont do anything. Tried to print the objects and all I get is undefined objects. Anyone know why this might be so?
Thanks in regards!

**Comment by gallexme** [comment]
do you await it?

**Comment by BloodBowMain** [comment]
I am assigning await Poke.GetMapObjects to a constant called cell (believe that is your "objects"?) then using it in a for of loop for(let checkpoint of cell.forts.checkpoints) It is at this point I added a console.log(toString(checkpoint)) only getting undefined objects therefore not going further in my system...

**Comment by gallexme** [comment]
weird

**Comment by BloodBowMain** [comment]
```
function retry(){
init()
}

try{
async function init() {

  Poke.player.location = {
    latitude: parseFloat(lat),
    longitude: parseFloat(lng),
  }

  const api = await Poke.login(username, password, provider)

  let player = await Poke.GetPlayer()

  while( true ){

let cell = await Poke.GetMapObjects()    


for (let checkpoint of cell.forts.checkpoints) {
      if (!checkpoint.cooldown && checkpoint.withinRange) {
        let res = await checkpoint.search()
        console.log(res)
      }
    }

    await Poke.player.walkAround()


    await new Promise(resolve => setTimeout(resolve, 3000))
  
}

init().catch(console.log)
}
catch(err){
console.log(err)
retry()
}
```

**Comment by BloodBowMain** [comment]
Okey, so all of a sudden I'm getting a FortSearchResponse, thanks!
