### ISSUE TITLE
Make POGOProtos a submodule?

### ISSUE THREAD

**Issue by jimmywarting** [stoffern/pokemongo-api#89]
Then it can always be up to date with https://github.com/AeonLucid/POGOProtos/tree/master/src/POGOProtos

**Comment by stoffern** [comment]
Yeha, i am back home in business :) I will update the Protos

**Comment by jimmywarting** [comment]
Welcome back!

**Comment by jimmywarting** [comment]
Or just use https://github.com/rastapasta/pokemon-go-protobuf-node

**Comment by stoffern** [comment]
@jimmywarting i will do alot of the issues now, and make a new big version number..
also fix so that the commitizen works with auto push to npm :smile:

**Comment by gallexme** [comment]
am im the only one?
TypeError: Cannot convert undefined or null to object
    at PokemonGOAPI._callee2$ (F:\Entwicklung\Pokemon\bot\web\node_modules\pokemongo-api\dist\index.js:167:35)

https://github.com/stoffern/pokemongo-api/blob/master/src/index.js#L91

**Comment by gallexme** [comment]
PokemonGOAPI.POGOProtos.Inventory.ItemId
should be
PokemonGOAPI.POGOProtos.Inventory.Item.ItemId

PokemonGOAPI.POGOProtos.Inventory.Item
should be
PokemonGOAPI.POGOProtos.Inventory.Item.ItemData

theres way more to fix too :/ new protos killed most things

**Comment by stoffern** [comment]
we will stick to this POGO protos..

**Comment by bensleveritt** [comment]
I'd love to see a protobufjs equivalent to https://github.com/rastapasta/pokemon-go-protobuf-node. Is this still on the cards? @stoffern

**Comment by stoffern** [comment]
@bensleveritt yes

**Comment by stoffern** [comment]
moved: d0d0a9d8918d8c90e7ff09adb74e0a6d415d15dd
